
    export const ActionTypes = {
        GET_MOVIES_LIST: "GET_MOVIES_LIST",
        ADD_TO_FAVORITE: "ADD_TO_FAVORITE",
        SELECTED_MOVIE: "SELECTED_MOVIE",
        REMOVE_FROM_FAVORITE: "REMOVE_FROM_FAVORITE"
    }
  

